import React, { useState } from 'react';
import './kraken.css';
const gbp = n => Number.isFinite(n) ? new Intl.NumberFormat('en-GB', { style: 'currency', currency: 'GBP' }).format(n) : 'Unavailable';
const pct = bps => Number.isFinite(bps) ? `${(bps / 100).toFixed(2)}%` : '—';
const price = n => Number.isFinite(n) ? new Intl.NumberFormat('en-GB', { style: 'currency', currency: 'GBP', minimumFractionDigits: 2, maximumFractionDigits: 10 }).format(n) : '—';
const time = at => new Date(at).toLocaleString('en-GB');
const fields = [
  ['spend', 'Buy budget · GBP', 5, 100, 1], ['feePct', 'Taker fee each way · %', 0, 2, 0.01],
  ['momentumBps', 'Trend threshold / bps', 10, 2000, 10], ['lookbackSec', 'Trend window / seconds', 60, 3600, 60], ['confirmBps', '60s confirmation / bps', 0, 100, 1], ['maxSpreadBps', 'Maximum spread / bps', 1, 100, 1], ['bufferBps', 'Adverse buffer each way · bps', 0, 100, 1],
  ['takeProfit', 'Net profit target · GBP', 0.1, 100, 0.1], ['stopLoss', 'Net loss trigger · GBP', 0.1, 10, 0.05],
  ['maxHoldSec', 'Maximum hold · seconds', 60, 86400, 60],
];
export default function KrakenPanel({ account: a, connection, notify }) {
  const [draft, setDraft] = useState(null), [busy, setBusy] = useState(false);
  if (!a) return <div className="panel">Connecting to the Kraken paper engine…</div>;
  const accountConnection = a.accountConnection || {};
  const rules = draft || a.settings, open = a.trades.filter(t => t.status === 'open');
  const disabled = busy || connection !== 'live' || Boolean(a.persistenceError);
  const action = async (path, body) => {
    setBusy(true);
    try {
      const response = await fetch(`/api/kraken/${path}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
      const data = await response.json(); if (!response.ok) throw Error(data.error || 'Request failed');
      if (path === 'settings') setDraft(null);
      notify(data.message);
    } catch (error) { notify(error.message); } finally { setBusy(false); }
  };
  return <div className="kraken">
    <div className="kraken-banner"><div><b>Kraken Pro spot · GBP</b><p>Live market data. Separate £1,000 simulated account. No real orders.</p></div><span className="source">PAPER MODE</span></div>
    <section className="feed-strip" aria-label="Kraken stream performance">
      <div><span>Kraken WebSocket v2</span><strong className={a.feed.status === 'connected' && a.online ? 'positive' : 'negative'}>{a.feed.status} · {a.online ? 'online' : 'not ready'}</strong><small>{a.feed.reconnects || 0} reconnects · {a.scan.filter(q => q.fresh).length}/{a.scan.length} fresh pairs</small></div>
      <div><span>Bid / ask updates</span><strong>{a.updates.toLocaleString()}</strong><small>Scan on every update · 100 ms exit checks</small></div>
      <div><span>Stream round trip</span><strong>{Number.isFinite(a.feed.roundTripMs) ? `${Math.round(a.feed.roundTripMs)} ms` : 'Measuring…'}</strong><small>Paper latency: 250 ms per order</small></div>
    </section>
    {(a.persistenceError || a.metadataError || a.feed.error) && <div className="notice" role="alert">{a.persistenceError || a.metadataError || a.feed.error}</div>}
    <div className="paper-summary"><div><span>Paper cash · GBP</span><strong>{gbp(a.cash)}</strong></div><div><span>Paper equity · net exit value</span><strong>{gbp(a.equity)}</strong></div><div><span>Realized paper P&amp;L</span><strong className={a.realizedNet >= 0 ? 'positive' : 'negative'}>{gbp(a.realizedNet)}</strong></div><div><span>Unrealized paper P&amp;L</span><strong className={a.unrealizedNet >= 0 ? 'positive' : 'negative'}>{gbp(a.unrealizedNet)}</strong></div></div>
    <section className="panel"><h2>Meme tokens vs majors · auto trend paper results</h2><p>Same GBP cash pool and one-position limit. These are observed results, not an independent backtest. Manual trades are excluded.</p>{a.comparison?.map(g => <div className="settings-row" key={g.category}><span>{g.category}: {g.closed} closed / {g.open} open</span><b>Net {gbp(g.net)} · Worst trade {gbp(g.worstTrade)}</b></div>)}</section>
    <section className="panel"><h2>Triangle scanner · snapshot estimates</h2><p>Four routes, starting with {gbp(a.settings.spend)}. Uses bid/ask, three verified taker fees, adverse buffers, minimum sizes and full best-level liquidity. No orders or paper profits are booked. Quotes can change between legs; crypto dust is excluded from GBP returns. Refresh fees with Check Kraken account.</p>{a.triangles?.map(t => <div key={t.route}><h3>{t.route}</h3><p>{t.status} · Returned {gbp(t.returnedGbp)} · Net <b className={t.net > 0 ? 'positive' : 'negative'}>{gbp(t.net)}</b></p><small>{t.legs.map(l => `${l.side} ${l.symbol}: ${l.feePct}% fee (${l.fee.toPrecision(4)} ${l.feeCurrency})`).join(' / ')}</small></div>)}</section>
    <section className="kraken-markets" aria-label="Kraken GBP markets">{a.scan.map(q => <article className="panel" key={q.symbol}>
      <div className="panel-head"><h2>{q.symbol} <small>{q.category}</small></h2><span className={`source ${q.fresh ? 'positive' : 'negative'}`}>{q.fresh ? 'LIVE' : 'WAITING'}</span></div>
      <div className="kraken-price">{Number.isFinite(q.ask) ? price(q.ask) : '—'}<small>Buy ask · sell bid {Number.isFinite(q.bid) ? price(q.bid) : '—'}</small></div>
      <div className="settings-row"><span>Move over {a.settings.lookbackSec / 60}m</span><b>{pct(q.moveBps)}</b></div>
      <div className="settings-row"><span>Rise needed to break even*</span><b>{pct(q.breakEvenBps)}</b></div>
      <div className="settings-row"><span>60s confirmation / required</span><b>{pct(q.confirmBps)} / {pct(a.settings.confirmBps)}</b></div><div className="settings-row"><span>History ready</span><b>{q.historySec}/{a.settings.lookbackSec}s</b></div><div className="settings-row"><span>Rise needed for net profit target</span><b>{pct(q.targetRiseBps)}</b></div><div className="settings-row"><span>Estimated immediate exit loss</span><b>{gbp(q.initialLoss)}</b></div><div className="settings-row"><span>{q.feeSource} / side</span><b>{q.feePct?.toFixed(2)}%</b></div><p className="kraken-reason">{q.reason}</p>
      <button disabled={disabled || !q.entryAllowed} onClick={() => action('enter', { symbol: q.symbol })}>Paper buy {q.symbol.split('/')[0]} · {gbp(a.settings.spend)}</button>
    </article>)}</section>
    <div className="scan-status" role="status">{a.pending ? `${a.pending.symbol}: paper entry pending` : a.lastAction}</div>
    <div className="paper-layout kraken-controls"><section className="panel">
      <div className="panel-head"><div><h2>Trend + confirmation experiment</h2><span>Rank sustained rises with short-term confirmation; exit by net P&amp;L or time</span></div><span className="source">{a.settings.autoEnabled ? 'AUTO PAPER ON' : 'AUTO PAPER OFF'}</span></div>
      <p>This is an unhedged spot strategy. A past rise does not predict the next move. It is not arbitrage and has no demonstrated profit edge.</p>
      <div className="inputs paper-inputs">{fields.map(([key, label, min, max, step]) => <label key={key}>{label}<input aria-label={label} type="number" min={min} max={max} step={step} value={rules[key]} onChange={e => setDraft({ ...rules, [key]: e.target.value })}/></label>)}</div>
      <div className="paper-actions"><button disabled={disabled} onClick={() => action('settings', { ...rules, ...Object.fromEntries(fields.map(([key]) => [key, Number(rules[key])])) })}>Save paper settings</button><button disabled={disabled} className={a.settings.autoEnabled ? 'stop' : 'start'} onClick={() => action('settings', { ...a.settings, autoEnabled: !a.settings.autoEnabled })}>{a.settings.autoEnabled ? 'Stop auto paper entries' : 'Start auto paper entries'}</button></div>
      <p>One open position · 60s entry cooldown · £10 daily realized loss limit (UTC). Exits continue when auto entries are off. Stop prices are triggers, not guaranteed fills.</p>
    </section><section className="panel"><h2>Your Kraken account</h2><p><b>{accountConnection.connected ? 'Account connected' : accountConnection.apiKeyStored && accountConnection.secretStored ? 'Encrypted keys stored · ready to check' : 'Account not connected'}</b></p>{accountConnection.connected && <><div className="settings-row"><span>Available real GBP · not paper cash</span><b>{gbp(accountConnection.gbpBalance)}</b></div><p>Available balance excludes order holds and borrowed credit. Last checked {time(accountConnection.checkedAt)}.</p>{Object.entries(accountConnection.feePctByPair || {}).map(([pair, fee]) => <div className="settings-row" key={pair}><span>{pair} · account taker fee</span><b>{fee.toFixed(2)}%</b></div>)}</>}{accountConnection.error && <p role="alert">{accountConnection.error}</p>}<p>This tab uses paper trades. Use the separate Kraken live tab for manual real orders. API keys stay encrypted in your Windows account outside the project; no withdrawal access is needed.</p><button disabled={disabled} onClick={() => action('account/check', {})}>{busy ? 'Checking…' : 'Check Kraken account'}</button><h2>What the simulation assumes</h2><p>Buys use the ask and sells use the bid after 250 ms, plus the fee and adverse price buffer. The whole quantity must fit the displayed best level. No deeper liquidity or partial fills are invented. Best-level snapshots can still change before a real order arrives.</p><p>*Break-even includes spread, both fees and both buffers. Fresh verified account rates override the configured fee assumption for each pair. Use Check Kraken account to refresh rates; after one hour the simulation returns to the configured assumption. The trend signal is separate from trading costs. Past movement is not a forecast of future gains. Auto entries reject spreads above your limit, insufficient history, and costs that already exceed the loss trigger.</p><p>Exit valuation is unavailable when quotes or sufficient bid quantity are missing. Existing positions retain the settings saved at entry.</p><div className="source-links"><a href="https://www.kraken.com/features/fee-schedule" target="_blank" rel="noreferrer">Kraken fee schedule ↗</a><a href="https://docs.kraken.com/exchange/api-reference/spot-websocket-v2/ticker" target="_blank" rel="noreferrer">Market stream documentation ↗</a></div></section></div>
    <section className="panel table-panel"><div className="panel-head"><div><h2>Kraken paper trades</h2><span>{open.length} open · {a.trades.length} total · GBP ledger</span></div><a className="button" href="/api/kraken/trades.csv">Export Kraken CSV</a></div><div className="table-wrap"><table><thead><tr><th>Entered</th><th>Pair / mode</th><th>Status</th><th>Quantity</th><th>Entry cost</th><th>Fees</th><th>Net P&amp;L</th><th>Exit</th></tr></thead><tbody>{a.trades.length ? a.trades.map(t => <tr key={t.id}><td>{time(t.openedAt)}</td><td>{t.symbol}<small>{t.mode}</small></td><td>{t.status}<small>{t.exitBlocked || t.exitReason}</small></td><td>{t.quantity.toFixed(8)}</td><td>{gbp(t.totalCost)}</td><td>{gbp(t.entryFee + (t.exitFee || 0))}</td><td className={(t.status === 'closed' ? t.realizedNet : t.unrealizedNet) >= 0 ? 'positive' : 'negative'}>{gbp(t.status === 'closed' ? t.realizedNet : t.unrealizedNet)}<small>{t.status === 'closed' ? 'Realized' : 'Net exit estimate'}</small></td><td>{t.status === 'open' ? <button disabled={disabled || Boolean(t.exitReason)} onClick={() => action('close', { tradeId: t.id })}>{t.exitReason ? 'Exit pending' : 'Close paper trade'}</button> : time(t.closedAt)}</td></tr>) : <tr><td colSpan="8" className="empty-table">No trades yet. Use a paper buy to test the ledger, or enable auto paper entries and wait for the stated momentum threshold.</td></tr>}</tbody></table></div></section>
  </div>;
}
