import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';
import './paper.css';
import { freshBook } from '../order-book.mjs';
import './streams.css';
import ScalperPanel from './ScalperPanel.jsx';
import KrakenPanel from './KrakenPanel.jsx';
import KrakenMakerPanel from './KrakenMakerPanel.jsx';
import KrakenLivePanel from './KrakenLivePanel.jsx';
import ObservationStatus from './ObservationStatus.jsx';

const money = (n, digits=2) => Number.isFinite(n) ? (n < 0 ? '-$' : '$') + Math.abs(n).toLocaleString('en-US', { minimumFractionDigits: digits, maximumFractionDigits: digits }) : '—';
const fixed = (n, digits=2) => Number.isFinite(n) ? n.toFixed(digits) : '—';
const time = ts => ts ? new Date(ts).toLocaleTimeString('en-GB', { hour12:false }) : '—';
const age = ts => ts ? `${Math.max(0, Math.floor((Date.now()-ts)/1000))}s ago` : 'No data';
function best(levels, side) {
  const list = (levels || []).map(x => ({ price:Number(x.price), size:Number(x.size) })).filter(x => Number.isFinite(x.price) && x.size > 0);
  list.sort((a,b) => side === 'ask' ? a.price-b.price : b.price-a.price);
  return list[0];
}
function Sparkline({ points }) {
  if (points.length < 2) return <div className="chart-empty">Waiting for BTC price history…</div>;
  const values = points.map(x => x.price), lo = Math.min(...values), hi = Math.max(...values), range = Math.max(hi-lo, 1);
  const coordinates = points.map((p,i) => `${i/(points.length-1)*100},${88-(p.price-lo)/range*72}`).join(' ');
  return <svg className="chart" viewBox="0 0 100 100" preserveAspectRatio="none" aria-label="Binance BTC mid-price history"><line x1="0" y1="88" x2="100" y2="88" stroke="#293541" strokeWidth=".3"/><line x1="0" y1="52" x2="100" y2="52" stroke="#293541" strokeWidth=".3"/><line x1="0" y1="16" x2="100" y2="16" stroke="#293541" strokeWidth=".3"/><polyline fill="none" stroke="#6ce0cf" strokeWidth=".8" vectorEffect="non-scaling-stroke" points={coordinates}/></svg>;
}
function App() {
  const [state, setState] = useState(null), [tab, setTab] = useState(() => new URLSearchParams(window.location.search).get('tab') === 'maker' ? 'Kraken maker' : 'Kraken spot');
  const [selected, setSelected] = useState(''), [shares, setShares] = useState(10), [buffer, setBuffer] = useState(25);
  const [paused, setPaused] = useState(false), [message, setMessage] = useState('');
  const [paperDraft, setPaperDraft] = useState(null);
  const [connection, setConnection] = useState('connecting'), [deliveryMs, setDeliveryMs] = useState(null);
  const [, setClock] = useState(0);
  useEffect(() => { const timer = setInterval(() => setClock(n => n + 1), 500); return () => clearInterval(timer); }, []);
  useEffect(() => {
    if (paused) { setConnection('paused'); return; }
    setConnection('connecting');
    const stream = new EventSource('/api/stream');
    stream.onmessage = event => {
      const data = JSON.parse(event.data);
      setState(data);
      setPaperDraft(current => current || data.paper?.settings || null);
      setDeliveryMs(Math.max(0, Date.now() - data.sentAt));
      setConnection('live');
    };
    stream.onerror = () => setConnection('reconnecting');
    return () => stream.close();
  }, [paused]);
  const markets = state?.markets || [];
  const market = markets.find(m => m.id === selected) || markets[0];
  const quote = useMemo(() => {
    if (!market?.books || market.feeType !== 'crypto_fees_v2') return null;
    const n = Number(shares), b = Number(buffer);
    if (!Number.isFinite(n) || n < 5 || !Number.isFinite(b) || b < 0 || b > 500) return null;
    const walk = levels => { let left=n,cost=0,fees=0; const sorted=[...levels].sort((a,b)=>Number(a.price)-Number(b.price)); for (const l of sorted) { const p=Number(l.price), take=Math.min(left,Number(l.size)); if (!(p>0&&p<1&&take>0)) continue; cost+=take*p; fees+=take*.07*p*(1-p); left-=take; if(left<1e-8)break; } return {complete:left<1e-8,cost,fees}; };
    const up=walk(market.books.up.asks||[]), down=walk(market.books.down.asks||[]);
    if (!up.complete||!down.complete) return {available:false};
    const fee=up.fees+down.fees, executionBuffer=(up.cost+down.cost)*b/10000, net=n-up.cost-down.cost-fee-executionBuffer;
    return {available:true,up,down,fee,executionBuffer,net,gross:n-up.cost-down.cost};
  },[market,shares,buffer]);
  const stale = ['Kraken spot', 'Kraken live', 'Kraken maker'].includes(tab) ? connection !== 'live' || state?.kraken?.feed?.status !== 'connected' || !state?.kraken?.online : connection !== 'live' || state?.feeds?.polymarket?.status !== 'connected' ||
    state?.feeds?.binance?.status !== 'connected' || !markets.some(m => freshBook(m)) ||
    !state?.binance?.fetchedAt || Date.now()-state.binance.fetchedAt>12000;
  const bookStale = connection !== 'live' || !freshBook(market);
  const capture = async () => { try { const r=await fetch('/api/capture',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({marketId:market.id,shares:Number(shares),bufferBps:Number(buffer)})}); const d=await r.json(); if(!r.ok) throw Error(d.error||'Capture failed'); setMessage('Fresh quote snapshot saved below. The price may differ from the previous screen. No paper pair was entered.'); } catch(e){setMessage(e.message);} };
  const paperEnter = async () => { try { const r=await fetch('/api/paper/enter',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({marketId:market.id,shares:Number(shares),bufferBps:Number(buffer)})}); const d=await r.json(); if(!r.ok) throw Error(d.error||'Paper entry failed'); setMessage('Paper pair entered at a fresh quote. Both fills are assumed, not verified.'); setTab('Paper trades'); } catch(e){setMessage(e.message);} };
  const savePaperSettings = async (autoEnabled = paperDraft?.autoEnabled) => { try { const body={...paperDraft,autoEnabled,shares:Number(paperDraft.shares),bufferBps:Number(paperDraft.bufferBps),minNetUsd:Number(paperDraft.minNetUsd),maxOpen:Number(paperDraft.maxOpen)}; const r=await fetch('/api/paper/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}); const d=await r.json(); if(!r.ok) throw Error(d.error||'Settings failed'); setPaperDraft(d.settings); setMessage(`Auto paper trading ${d.settings.autoEnabled?'enabled':'disabled'}. Settings saved.`); } catch(e){setMessage(e.message);} };
  const paper=state?.paper;
  const paperOpen=paper?.trades?.filter(t=>t.status==='open')||[];
  const paperSettled=paper?.trades?.filter(t=>t.status==='settled')||[];
  const realized=paperSettled.reduce((n,t)=>n+t.realizedNet,0);
  const projected=paperOpen.reduce((n,t)=>n+t.projectedNet,0);
  const nav=['Kraken spot','Kraken live','Kraken maker','Latency scalper','Monitor','Opportunities','Paper trades','Settings'];
  return <div className="app">
    <aside className="sidebar"><div className="brand">Edge Lab<span>Market research</span></div><nav>{nav.map((name,i)=><button key={name} className={tab===name?'active':''} onClick={()=>setTab(name)}><span className="nav-icon">{['◈','£','⇄','↗','▥','◇','▤','⚙'][i]}</span>{name}</button>)}</nav><div className="side-foot"><span className={`dot ${stale?'warn':''}`}/>{stale?'Feed delayed':'Local feed active'}<small>Paper + manual Kraken<br/>API keys encrypted locally</small></div></aside>
    <main><header><div><h1>{tab}</h1><p>{tab==='Kraken live'?'Your real Kraken account · manual orders':tab==='Kraken spot'?'Live GBP markets · separate paper account':tab==='Kraken maker'?'Maker entry and triangle conversion · paper experiment':tab==='Latency scalper'?'Single-outcome lead/lag experiment':tab==='Monitor'?'BTC paired-market monitor':tab==='Opportunities'?'Observed two-sided price gaps':tab==='Paper trades'?'Paired account: assumed fills and verified settlement':'Research assumptions and sources'}</p></div><div className="header-actions"><span className={`status ${stale?'warning':''}`}><span className="dot"/> {paused?'Display paused':stale?'Connecting / delayed':'Streaming'} · {age(state?.updatedAt)}</span><button onClick={()=>setPaused(!paused)}>{paused?'Resume display':'Pause display'}</button><a className="button" href={tab==='Kraken live'?'/api/kraken/live-orders.csv':tab==='Kraken spot'?'/api/kraken/trades.csv':tab==='Kraken maker'?'/api/kraken/maker/trades.csv':tab==='Latency scalper'?'/api/scalper/trades.csv':tab==='Paper trades'?'/api/paper/trades.csv':'/api/observations.csv'}>Export CSV</a></div></header>
    {!['Kraken spot','Kraken live','Kraken maker'].includes(tab)&&<section className="feed-strip" aria-label="Live stream performance">
      <div><span>Polymarket stream</span><strong className={state?.feeds?.polymarket?.status==='connected'?'positive':'negative'}>{state?.feeds?.polymarket?.status||'connecting'}</strong><small>{state?.feeds?.polymarket?.syncedTokens||0}/{state?.feeds?.polymarket?.tokens||0} outcome books synced · {state?.feeds?.polymarket?.reconnects||0} reconnects</small></div>
      <div><span>Binance stream</span><strong className={state?.feeds?.binance?.status==='connected'?'positive':'negative'}>{state?.feeds?.binance?.status||'connecting'}</strong><small>BTC/USDT · {state?.feeds?.binance?.messages?.toLocaleString()||0} updates received</small></div>
      <div><span>Quote checks / second</span><strong>{fixed(state?.engine?.scansPerSecond,0)}</strong><small>On every book update · scan p95 {fixed(state?.engine?.processingP95Ms,2)} ms</small></div>
      <div><span>Polymarket round trip</span><strong>{fixed(state?.feeds?.polymarket?.roundTripMs,0)} ms</strong><small>Heartbeat timing · source delta {fixed(state?.feeds?.polymarket?.lagP50Ms,0)} ms (clock dependent)</small></div>
      <div><span>Screen delivery</span><strong>{connection==='live'?`${fixed(deliveryMs,0)} ms`:connection}</strong><small>Pushes up to 20/s · engine runs on every update</small></div>
    </section>}
    {paused&&<div className="notice">Display paused. The server continues scanning and any enabled auto paper trading continues.</div>}
    {message&&<div className="notice" role="status">{message}<button onClick={()=>setMessage('')} aria-label="Dismiss">×</button></div>}
    {tab==='Kraken live'&&state?.kraken&&<div className="kraken"><KrakenLivePanel account={state.kraken} connection={connection} notify={setMessage}/></div>}
    {tab==='Kraken maker'&&<KrakenMakerPanel account={state?.kraken} connection={connection} notify={setMessage}/>}
    {tab==='Kraken spot'&&<KrakenPanel account={state?.kraken} connection={connection} notify={setMessage}/>}
    {tab==='Latency scalper'&&<ScalperPanel account={state?.scalper} connection={connection} notify={setMessage}/>}
    {tab==='Monitor'&&<>
      <section className="top-grid"><div className="panel btc-panel"><div className="panel-head"><div><h2>Bitcoin / USDT</h2><span>Binance spot bid and ask · context feed</span></div><span className="source">BINANCE</span></div><div className="big-price">{money(state?.binance?.mid)}<small>{state?.binance?`Bid ${money(state.binance.bid)}  /  Ask ${money(state.binance.ask)}`:'Waiting for feed'}</small></div><Sparkline points={state?.history||[]}/><div className="chart-caption"><span>30 minutes of local observations</span><span>Last sample {age(state?.binance?.fetchedAt)}</span></div></div>
      <div className="panel market-panel"><div className="panel-head"><div><h2>BTC Up / Down</h2><span>Choose an open Polymarket contract</span></div><span className="source">POLYMARKET</span></div><select aria-label="Market" value={market?.id||''} onChange={e=>setSelected(e.target.value)}>{markets.map(m=><option value={m.id} key={m.id}>{m.title}</option>)}</select>{market?<><div className="market-title">{market.title}</div><div className="outcomes">{['up','down'].map(side=>{const b=market.books?.[side];const ask=best(b?.asks,'ask'),bid=best(b?.bids,'bid');return <div className={`outcome ${side}`} key={side}><b>{side.toUpperCase()}</b><strong>{ask?`${fixed(ask.price*100,1)}¢`:'—'}</strong><small>Best ask in USDC: {ask?fixed(ask.price,3):'—'}</small><small>Ask depth: {ask?fixed(ask.size,1):'—'} shares</small><small>Best bid: {bid?fixed(bid.price,3):'—'}</small></div>})}</div><div className="meta"><span>Ends {new Date(market.endDate).toLocaleTimeString('en-GB',{hour12:false})}</span><span>Book {age(market.bookFetchedAt)}</span></div><a className="market-link" href={market.url} target="_blank" rel="noreferrer">Open market ↗</a></>:<div className="empty">No open market found. The app will keep checking.</div>}</div></section>
      <section className="lower-grid"><div className="panel calculator"><div className="panel-head"><div><h2>Two-sided paper quote</h2><span>Equal Up and Down shares, held through resolution</span></div><span className="source">ESTIMATE</span></div><div className="inputs"><label>Paired shares<input type="number" min="5" step="1" value={shares} onChange={e=>setShares(e.target.value)}/></label><label>Execution buffer · bps<input type="number" min="0" max="500" step="5" value={buffer} onChange={e=>setBuffer(e.target.value)}/></label></div><div className="calc-rows"><div><span>Up ask cost</span><b>{quote?.available?money(quote.up.cost):'—'}</b></div><div><span>Down ask cost</span><b>{quote?.available?money(quote.down.cost):'—'}</b></div><div><span>Estimated taker fees</span><b>{quote?.available?money(quote.fee):'—'}</b></div><div><span>Execution buffer</span><b>{quote?.available?money(quote.executionBuffer):'—'}</b></div><div className="total"><span>Estimated net at settlement</span><b className={quote?.net>0?'positive':'negative'}>{quote?.available?money(quote.net):'Unavailable'}</b></div></div><div className="calc-bottom"><p>{bookStale?'Order book is stale. Paper entry is disabled.':!quote?.available?'Insufficient depth or invalid size.':quote.net<0?`This pair loses ${money(Math.abs(quote.net))} at the displayed asks after costs. Auto mode skips it.`:'Both paper fills are assumed at the observed asks plus costs.'}</p><div className="action-group"><button disabled={bookStale||!quote?.available} onClick={capture}>Record quote only</button><button disabled={bookStale||!quote?.available} onClick={paperEnter}>Enter paper trade</button></div></div></div>
      <div className="panel method"><h2>What this tests</h2><div className="method-step"><span>01</span><div><b>Real ask depth</b><p>Walk both books for the full share count, rather than using midpoint prices.</p></div></div><div className="method-step"><span>02</span><div><b>Fees and execution buffer</b><p>Apply Polymarket crypto taker fees to each leg and a user-set extra cost.</p></div></div><div className="method-step"><span>03</span><div><b>Observe, then validate</b><p>Record apparent gaps. A quote is not proof that both orders would fill.</p></div></div><div className="source-note">These markets resolve from Chainlink TWAP. Binance spot is shown only as context.</div></div></section>
      <ObservationStatus state={state} connection={connection}/>
      <ObservationTable rows={state?.observations||[]} limit={8}/>
    </>}
    {tab==='Opportunities'&&<><ObservationStatus state={state} connection={connection}/><ObservationTable rows={(state?.observations||[]).filter(x=>x.type==='Observed gap')}/></>}
    {tab==='Paper trades'&&<><div className="paper-summary"><div><span>Paper cash</span><strong>{money(paper?.cash)}</strong></div><div><span>Open pairs</span><strong>{paperOpen.length}</strong></div><div><span>Projected net on open pairs</span><strong className={projected>=0?'positive':'negative'}>{money(projected)}</strong></div><div><span>Realized paper P&amp;L</span><strong className={realized>=0?'positive':'negative'}>{money(realized)}</strong></div></div><div className="paper-layout"><div className="panel"><div className="panel-head"><div><h2>Auto paper entries</h2><span>Positive net after ask depth, fees, and buffer</span></div><span className="source">{paper?.settings?.autoEnabled?'RUNNING':'OFF'}</span></div><div className="scan-status">{paper?.lastScan ? `${paper.lastScan.eligible} of ${paper.lastScan.markets} markets currently qualify · ${paper.lastScan.priced} have full fresh ask depth · best net ${money(paper.lastScan.bestNet)}` : 'Waiting for first market scan.'}</div><div className="inputs paper-inputs"><label>Paired shares<input type="number" min="5" max="1000" step="1" value={paperDraft?.shares??10} onChange={e=>setPaperDraft({...paperDraft,shares:e.target.value})}/></label><label>Buffer · bps<input type="number" min="0" max="500" step="5" value={paperDraft?.bufferBps??25} onChange={e=>setPaperDraft({...paperDraft,bufferBps:e.target.value})}/></label><label>Minimum net · USD<input type="number" min="0" max="100" step="0.01" value={paperDraft?.minNetUsd??.10} onChange={e=>setPaperDraft({...paperDraft,minNetUsd:e.target.value})}/></label><label>Max open pairs<input type="number" min="1" max="10" step="1" value={paperDraft?.maxOpen??2} onChange={e=>setPaperDraft({...paperDraft,maxOpen:e.target.value})}/></label></div><div className="paper-actions"><button onClick={()=>savePaperSettings()}>Save settings</button><button className={paper?.settings?.autoEnabled?'stop':'start'} onClick={()=>savePaperSettings(!paper?.settings?.autoEnabled)}>{paper?.settings?.autoEnabled?'Stop auto paper':'Start auto paper'}</button></div></div><div className="panel"><h2>How paper P&amp;L works</h2><p>Each entry assumes the displayed asks on both legs could be filled together. Paper cash is debited by both costs, fees, and buffer. The net stays projected while the market is open.</p><p>When Gamma reports a resolved binary outcome, the pair receives one USDC per share. Only then does its net move into realized paper P&amp;L.</p><p>Auto entry is off by default. Manual “Enter paper trade” on Monitor can record a losing quote too, so you can test the ledger.</p></div></div><PaperTradeTable rows={paper?.trades||[]}/></>}
    {tab==='Settings'&&<div className="settings-grid"><div className="panel"><h2>Current assumptions</h2><div className="settings-row"><span>Markets</span><b>BTC 5m and 15m, current and next</b></div><div className="settings-row"><span>Market refresh</span><b>20 seconds</b></div><div className="settings-row"><span>Book and Binance updates</span><b>Live WebSocket streams</b></div><div className="settings-row"><span>Paper decisions</span><b>On every book update</b></div><div className="settings-row"><span>Screen updates</span><b>Pushed up to 20 times / second</b></div><div className="settings-row"><span>Crypto taker fee</span><b>0.07 × shares × price × (1 − price)</b></div><div className="settings-row"><span>Paper size</span><b>Editable on Monitor and Paper trades</b></div><div className="settings-row"><span>Execution buffer</span><b>Editable on Monitor and Paper trades</b></div></div><div className="panel"><h2>Data and limitations</h2><p>Gamma supplies open market metadata and verified resolution; CLOB supplies order books; Binance supplies BTC spot bid and ask. Source errors remain visible below. The local server saves quote observations to <code>data/observations.json</code> and paper positions to <code>data/paper-v1.json</code>.</p><p>Binary payouts assume one Up and one Down share cover every resolution. Paper entry assumes both displayed asks fill together. Real order rejection, partial fills, settlement delays, and platform availability are not simulated. Polymarket remains paper-only. The separate Kraken live tab supports manual real orders using encrypted API credentials.</p><div className="source-links"><a href="https://docs.polymarket.com/trading/fees" target="_blank" rel="noreferrer">Polymarket fee formula ↗</a><a href="https://docs.polymarket.com/market-data/realtime-data" target="_blank" rel="noreferrer">Polymarket market data ↗</a><a href="https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-streams.md" target="_blank" rel="noreferrer">Binance market data ↗</a></div></div><div className="panel error-panel"><h2>Source health</h2>{Object.keys(state?.errors||{}).length?Object.entries(state.errors).map(([k,v])=><p key={k}><b>{k}</b> {v}</p>):<p>No source errors reported.</p>}</div></div>}
    </main></div>;
}
function ObservationTable({rows,limit}) { const shown=limit?rows.slice(0,limit):rows; return <section className="panel table-panel"><div className="panel-head"><div><h2>Observation log</h2><span>{rows.length} saved snapshots</span></div></div><div className="table-wrap"><table><thead><tr><th>Time</th><th>Market</th><th>Type</th><th>Shares</th><th>Up cost</th><th>Down cost</th><th>Fees + buffer</th><th>Quote net</th></tr></thead><tbody>{shown.length?shown.map(x=><tr key={x.id}><td>{time(x.at)}</td><td title={x.title}>{x.slug}</td><td>{x.type}</td><td>{x.shares}</td><td>{money(x.upCost)}</td><td>{money(x.downCost)}</td><td>{money(x.fees+x.buffer)}</td><td className={x.net>0?'positive':'negative'}>{money(x.net)}</td></tr>):<tr><td colSpan="8" className="empty-table">No snapshots yet. Watch live books or save a paper quote.</td></tr>}</tbody></table></div></section> }
function PaperTradeTable({rows}) { return <section className="panel table-panel"><div className="panel-head"><div><h2>Paper trade ledger</h2><span>{rows.length} assumed paired fills · settlement checked against Gamma</span></div></div><div className="table-wrap"><table><thead><tr><th>Entered</th><th>Market</th><th>Mode</th><th>Status</th><th>Shares</th><th>Cost</th><th>Projected net</th><th>Realized net</th></tr></thead><tbody>{rows.length?rows.map(t=><tr key={t.id}><td>{time(t.openedAt)}</td><td title={t.title}>{t.slug}</td><td>{t.mode}</td><td>{t.status==='settled'?`Settled · ${t.winner}`:'Open · awaiting resolution'}</td><td>{t.shares}</td><td>{money(t.totalCost)}</td><td className={t.projectedNet>=0?'positive':'negative'}>{money(t.projectedNet)}</td><td className={t.realizedNet>=0?'positive':'negative'}>{t.status==='settled'?money(t.realizedNet):'—'}</td></tr>):<tr><td colSpan="8" className="empty-table">No paper trades yet. Auto mode enters only when a market exceeds the net threshold; you can also use Enter paper trade on Monitor.</td></tr>}</tbody></table></div></section> }

const appRoot = import.meta.hot?.data.root || createRoot(document.getElementById('root'));
if (import.meta.hot) import.meta.hot.data.root = appRoot;
appRoot.render(<App/>);
